version: '3.8'

services:
  web:
    build: .
    command: python /code/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - 8000:8000
#    networks:
#      - djangonetwork
    depends_on:
      - db
  db:
    image: postgres:13
#    networks:
#      - djangonetwork
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"

#networks:
#    djangonetwork:
#        driver: bridge